# 最新版Docker Compose設定（十分なテスト後の使用推奨）
# ⚠️ 警告: ChromaDB 1.0.x系への移行は不可逆的です
# ⚠️ 使用前に必ずデータのフルバックアップを実行してください

services:
  # Main OKAMI service
  okami:
    build: .
    container_name: okami-main
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./knowledge:/app/knowledge
    environment:
      - PYTHONUNBUFFERED=1
      - CREWAI_STORAGE_DIR=/app/storage
      - CREWAI_DISABLE_TELEMETRY=true
      - OTEL_SDK_DISABLED=true
      - LOG_LEVEL=INFO
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_API_BASE_URL=http://ollama:11434  # 新バージョン用
      - EMBEDDER_PROVIDER=ollama
      - EMBEDDER_MODEL=mxbai-embed-large
      - VECTOR_STORE_TYPE=chroma
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      # ChromaDB 1.0.x系用の設定
      - CHROMA_PERSIST_DIRECTORY=
      - USE_QDRANT=false
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_HTTP_PORT=8000
      # CrewAI知識ベース用の設定
      - CREWAI__EMBEDDINGS__PROVIDER=ollama
      - CREWAI__EMBEDDINGS__MODEL=mxbai-embed-large
      - CREWAI__EMBEDDINGS__BASE_URL=http://ollama:11434
      # 新版での推奨設定
      - CREWAI_MEMORY_PROVIDER=basic
      - CREWAI_EMBEDDINGS_BATCH_SIZE=10
    env_file:
      - .env
    networks:
      - okami-network
    depends_on:
      - chromadb
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ChromaDB for vector storage（1.0.x系設定）
  chromadb:
    image: chromadb/chroma:1.0.20  # ⚠️ 最新版 - データ移行に注意
    container_name: okami-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/data  # 1.0.x系では /data がデフォルト
      - ./config/chroma:/chroma/config:ro  # 設定ファイル用（必要時）
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      # 1.0.x系の新しい認証設定（必要に応じて有効化）
      # - CHROMA_SERVER_AUTHN_CREDENTIALS_FILE=/chroma/config/credentials.json
      # - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.token.TokenAuthenticationServerProvider
      # - CHROMA_SERVER_AUTHZ_PROVIDER=chromadb.auth.simple.SimpleAuthorizationProvider
      # パフォーマンス設定
      - CHROMA_SEGMENT_CACHE_POLICY=LRU
      - CHROMA_COLLECTION_CACHE_SIZE=10
    networks:
      - okami-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Ollama for local embeddings（最新版）
  ollama:
    image: ollama/ollama:0.5.3  # 最新安定版
    container_name: okami-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./scripts/ollama-entrypoint.sh:/entrypoint.sh:ro
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=["*"]  # v0.5.0以降のCORS設定
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_DEBUG=1
      - OLLAMA_API_BASE_URL=http://0.0.0.0:11434
      # v0.5.x系の新機能設定
      - OLLAMA_THINKING_MODE=enabled  # 思考機能
      - OLLAMA_TOOL_SUPPORT=true      # ツールサポート
    networks:
      - okami-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  chroma-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/chroma  # 明示的なパス指定
  ollama-data:
    driver: local
    driver_opts:
      type: none  
      o: bind
      device: ./data/ollama  # 明示的なパス指定

networks:
  okami-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16  # 専用サブネット