evolution_task:
  description: |
    Analyze system performance metrics and agent behaviors to
    identify evolution opportunities. Generate actionable insights
    for system improvement and adaptation.
    
    User Input: {user_input}
    
    Main Crew Response: {main_response}
    
    You MUST output improvements in the following JSON format:
    ```json
    {
      "changes": [
        {
          "type": "update_agent_parameter",
          "agent": "agent_name",
          "parameter": "parameter_name",
          "value": new_value,
          "reason": "reason for change"
        },
        {
          "type": "add_knowledge",
          "file": "knowledge/filename.md",
          "content": "content to add",
          "reason": "reason for addition"
        }
      ]
    }
    ```
  
  expected_output: |
    A JSON object with the following structure:
    {
      "changes": [array of improvement items]
    }
    Each change must include: type, agent/file, parameter/content, value, and reason
  
  agent: evolution_agent
  
  output_json: EvolutionChanges
  
  # tools:
  #   - mcp
  #   - docker
  
  guardrail: |
    Recommendations must be data-driven, feasible to implement,
    and include measurable success criteria. Impact assessment
    required for each recommendation.
  
  max_retries: 2
  
  schedule: "0 */6 * * *"  # Run every 6 hours