simple_crew:
  name: "Simple Test Crew"
  description: "A minimal crew for testing basic functionality"
  process: "sequential"
  
  agents:
    - simple_research_agent
  
  tasks:
    - test_task
  
  memory: true  # 一時的に無効化（ChromaDB接続エラー回避）
  memory_config:
    provider: "basic"
  cache: true
  verbose: true
  
  # 知識管理を明示的に無効化
  knowledge_sources: []