simple_crew:
  name: "Simple Test Crew"
  description: "A minimal crew for testing basic functionality"
  process: "sequential"
  
  agents:
    - simple_research_agent
  
  tasks:
    - test_task
  
  # Memory設定（basicメモリとmem0 external memoryを併用）
  memory: true  # basicメモリを有効化
  # external_memoryはcrew_factory.pyで動的に設定される（mem0）
  memory_config:
    provider: "basic"  # 通常のメモリはbasicを使用
    config: {}
    user_memory: {}
  # Mem0設定（crew_factory.pyでexternal_memoryとして設定される）
  mem0_config:
    user_id: "okami_simple_crew"  # ユーザーID
    # org_id: "your_org_id"  # オプション
    # project_id: "your_project_id"  # オプション
  cache: true
  verbose: true
  
  # 知識管理を明示的に無効化
  knowledge_sources: []