test_crew:
  name: "Test Crew"
  description: "Simple test crew for OKAMI system verification"
  
  agents:
    - research_agent
    - analysis_agent
  
  tasks:
    - test_task
  
  process: sequential  # Use sequential for testing
  
  memory: true
  cache: true
  verbose: true